name: Build
on: [push, pull_request]

jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16.13.1
    - name: install dependencies
      run: yarn install
    - name: build
      run: yarn run make
